Homework 1
d1cies/todo-list-app pull request #1
Opened 2024-06-23 01:24 UTC by d1cies

useMaterial3: true

2024-06-23 11:50 UTC, coma8765 commented
Если какие-то вопросы / спорные моменты можешь писать в лс https://tg.me/coma8765

2024-06-23 13:26 UTC, coma8765 requested changes
## Часть 'Чистота кода и общая структура проекта (max 4 балла)'
**Итоговый балл**: 3

### Критерий 'Код консистентно отформатирован (+1 балл)'
Комментарий: визуально норм
**Балл:** +1

### Критерий 'readme' (+1 балл)
**Балл:** +1

### Критерий 'Код разбит на фичи и слои (+2 балла)'
Подобие чистой архитектуры имеется
Разбиение на слои присутствует, декомпозиция недостаточна.
**Балл**: 1 из 2

**Балл:** +2

## Часть 'Вёрстка + навигация (max 16 баллов)'
**Итоговый балл**: 16

### Полностью свёрстаны 2 экрана по макетам: основной и добавления/редактирования задачи (+10 баллов). Анимации не ожидаем.
Реализован
**Балл:** +10

### Реализован свайп по айтему Выполнено/Удалить, в качестве логики может быть просто коллбек (+3 балла)
Реализован
**Балл:** +3

### Показ выполненных дел (можно подложить просто stub, без логики) (+3 балла)
Реализован
**Балл:** +3

## Часть 'Разное (max 6 баллов)'
**Итоговый балл**: 5

### Реализовано логирование не print’ами, а сторонним или самописным logger’ом, логи которого не попадают в продакшен билд (+2 балла)
см. выше
**Балл:** +1 из 2

### У приложения есть иконка (iOS или Android, необязательно оба) (+4 балла)
**Балл:** +4

## Резюме
В целом выглядит хорошо на данном этапе

Балл пока на выставлен (выставлю после среды), но текущее состояние таково, балл возможно изменится, если я что-то пропустил (писать здесь или в тг)

2024-06-23 13:26 UTC, coma8765 commented on README.md
#### Критерии:
Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов (+1 балл)


- [x] APK лучше убрать в релиз
- [x] Фичи
- [x] скриншотов

балл: +1

2024-06-23 13:26 UTC, coma8765 commented on android/app/src/main/AndroidManifest.xml
#### Критерии:
У приложения есть иконка (iOS или Android, необязательно оба) (+4 балла)

- [x] iOS
- [x] Android

балл: +4

2024-06-23 13:26 UTC, coma8765 commented on lib/internal/di/configure_dependencies.dart
> +import 'package:get_it/get_it.dart';
лучше не использовать лекция 'архитектура часть 2'

2024-06-23 13:26 UTC, coma8765 commented on lib/internal/logger.dart
#### Критерии:
Реализовано логирование не print’ами, а сторонним или самописным logger’ом, логи которого не попадают в продакшен билд (+2 балла)

- [x] логирование не print’ами
- [x] не попадают в продакшен билд

балл: + 2 из 2х

2024-06-23 13:26 UTC, coma8765 commented on lib/presentation/common_components/loading_indicator.dart
> +          : CupertinoActivityIndicator(color: color),
хорошо сделано

2024-06-23 13:26 UTC, coma8765 commented on lib/presentation/todo_detail/todo_detail_screen/components/delete_element.dart
> +    final colors = Theme.of(context).extension<ThemeColors>()!;
Лучше избегать '!' т.к. может упасть в проде, можно заменить на что-то подобное
```
    final colors = Theme.of(context).extension<ThemeColors>() ?? ThemeColors() ;
```

2024-06-23 13:26 UTC, coma8765 commented on lib/presentation/todo_detail/todo_detail_screen/components/delete_element.dart
> +                      : colors.red,
Условный выражения в return сложно поддерживать, можно вывести как переменую перед return

2024-06-23 13:26 UTC, coma8765 commented on lib/presentation/todo_detail/todo_detail_screen/todo_detail_screen_widget.dart
> +class TodoDetailScreenWidget
Очень большой build, можно декомпозировать на приватные виджеты модуля

2024-06-23 13:26 UTC, coma8765 commented on lib/presentation/todo_list/todo_list_screen/components/sliver_persistent_app_bar.dart
> +            top: 130 - 100 * shift,
Сложно поддерживать неизвестные константные числа в выражениях, можно было вынести как приватные константы, например в начало модуля:

```
const _pageHeight = 999.0;
```

2024-06-23 13:46 UTC, d1cies commented on android/app/src/main/AndroidManifest.xml
на iOS тоже есть, скриншот в README

2024-06-23 13:50 UTC, d1cies commented on lib/internal/di/configure_dependencies.dart
> +import 'package:get_it/get_it.dart';
get_it + injectable один из самых распространенных пакетов для DI и ServiceLocator, предоставляющий инструмент для внедрения зависимостей. Здесь, мне кажется, больше вкусовщина, кто с чем работал и кому что зашло

2024-06-23 13:55 UTC, d1cies commented on lib/presentation/todo_list/todo_list_screen/components/sliver_persistent_app_bar.dart
> +            top: 130 - 100 * shift,
Тоже вкусовщина, я ориентируюсь на лекцию Fox, где он говорил об этом:
https://youtu.be/2PIusiLb3Pw?t=1953

2024-06-23 15:22 UTC, Strafe0 approved these changes

2024-06-23 15:22 UTC, Strafe0 commented on lib/presentation/todo_detail/todo_detail_screen/todo_detail_screen_widget.dart
> +class TodoDetailScreenWidget
Подтверждаю

2024-06-23 15:22 UTC, Strafe0 commented on lib/presentation/todo_detail/todo_detail_screen/todo_detail_screen_wm.dart
> +      // locale: const Locale('ru', 'RU'),
В `MaterialApp` можно добавить делегаты для локализации `DatePicker`

2024-06-23 15:22 UTC, Strafe0 commented on lib/presentation/todo_list/todo_list_screen/components/todo_item.dart
> +  Widget build(BuildContext context) {
Тоже можно подразбить на виджеты

2024-06-23 15:22 UTC, Strafe0 commented on lib/presentation/todo_list/todo_list_screen/components/visibility_button.dart
Не используется?

2024-06-23 22:00 UTC, coma8765 commented on android/app/src/main/AndroidManifest.xml
Принято

2024-06-23 22:05 UTC, coma8765 commented on lib/presentation/todo_list/todo_list_screen/components/sliver_persistent_app_bar.dart
> +            top: 130 - 100 * shift,
Прикольная лекция, спасибо за ссылку.

Пожалуй, соглашусь вкусовщина

2024-06-25 11:57 UTC, coma8765 commented on lib/presentation/common_components/loading_indicator.dart
> +          : CupertinoActivityIndicator(color: color),
но можно сделать лучше
https://docs.flutter.dev/platform-integration/platform-adaptations#widgets-with-adaptive-constructors

<img width="781" alt="Снимок экрана 2024-06-25 в 14 56 49" src="https://github.com/d1cies/todo-list-app/assets/68271457/11b6c91a-babc-4ec8-967a-7e0b3518b1fd">

2024-06-26 22:47 UTC, d1cies commented on lib/presentation/common_components/loading_indicator.dart
> +          : CupertinoActivityIndicator(color: color),
Да, хооший подход. Но вынос таких виджетов в кастомный модуль позволит потом при необходимосте быстро его изменить на что угодно

2024-06-26 22:48 UTC, d1cies commented on lib/presentation/todo_detail/todo_detail_screen/components/delete_element.dart
> +                      : colors.red,
дело вкуса

2024-06-26 22:50 UTC, d1cies commented on lib/presentation/todo_detail/todo_detail_screen/todo_detail_screen_widget.dart
> +class TodoDetailScreenWidget
да, декомпозиция важна. Если честно, то не успел все как следует декомпозировать, больше делал упор на полную реализцию всей логики приложения

2024-06-26 22:51 UTC, d1cies commented on lib/presentation/todo_detail/todo_detail_screen/todo_detail_screen_widget.dart
> +class TodoDetailScreenWidget
если возможно это учесть при оценке, я был бы признателен

2024-06-26 22:52 UTC, d1cies commented on lib/presentation/todo_detail/todo_detail_screen/todo_detail_screen_wm.dart
> +      // locale: const Locale('ru', 'RU'),
не встречался, спасибо, возьму на заметку

2024-06-26 23:20 UTC, d1cies commented on lib/internal/logger.dart
у пакета Logger  логи улетают в прод? не знал

2024-06-26 23:30 UTC, d1cies commented on lib/internal/logger.dart
я проверил по Logcat, в release сборке логи не идут

2024-06-27 18:31 UTC, coma8765 commented on lib/internal/logger.dart
Согласен, 2балла

2024-06-27 18:35 UTC, coma8765 commented
*Звездочка от меня за коммуникабельность

2024-06-27 23:15 UTC, merged

2024-07-01 10:16 UTC, f1xgun commented
Очень хорошая работа!

2024-07-01 10:16 UTC, f1xgun commented on lib/data/repository/local_todo_repository.dart
> +      StreamController.broadcast();
Можно создавать StreamController при инициализации репозитория, тогда у нас не будет создан контроллер, до тех пор пока это будет не нужно. Главное не забыть в этом случае удалить инстанс контроллера при dispose

2024-07-01 10:16 UTC, f1xgun commented on lib/presentation/todo_list/todo_list_screen/todo_list_screen_wm.dart
> +    todoListStreamSb?.cancel();
Еще обнулить инстанс было бы хорошо, через todoListStreamSb = null;